# Generated by Django 4.2.15 on 2024-08-13 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Which user created this article?', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='byline',
            field=models.CharField(help_text='What is your byline?', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(help_text='When will this be posted?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Local Government', 'Local Government'), ('National News', 'National News'), ('Tech', 'Tech'), ('Local Events', 'Local Events'), ('Reguional Affairs', 'Regional Affairs'), ('Business', 'Business'), ('Food', 'Food'), ('Tourism', 'Tourism'), ('Sports', 'Sports'), ('Arts and Culture', 'Arts and Culture'), ('Finance', 'Finance'), ('Crime', 'Crime')], default='0', help_text='What genre of news is this article?', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='What is the slug for this article?', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='What is the title of this article?', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='When was this updated?'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(help_text='What is the main theme of your comment?', max_length=150)),
                ('body', models.TextField(help_text='What do you want to say in your comment?', max_length=600)),
                ('review', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='What do you rate this article out of 10, where 10 is the best?', max_length=2)),
                ('approved', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post')),
            ],
        ),
    ]
