# Generated by Django 4.2.15 on 2024-08-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'status', 'ordering': ['-status']},
        ),
    ]
